---
#--------------------------------------------------------------#
# Install docker                                [docker_install]
#--------------------------------------------------------------#
- name: install docker and docker-compose
  tags: docker_install
  ignore_errors: true  # HOTFIX for EL8 Docker installation
  package: name={{ item }} state=present
  with_items:
    - docker-ce
    - docker-compose-plugin


#--------------------------------------------------------------#
# Add admin user to Docker group                  [docker_admin]
#--------------------------------------------------------------#
- name: add admin user to docker group
  ignore_errors: true
  tags: docker_admin
  user: name={{ item }} append=true groups=docker
  with_items:
    - "{% if node_user == 'root' %}{{ node_admin_username }}{% else %}{{ node_user }}{% endif %}"
    - "{{ node_admin_username }}"


#--------------------------------------------------------------#
# config docker                                  [docker_config]
#--------------------------------------------------------------#
- name: config docker
  tags: docker_config
  block:
    - name: create /etc/docker config dir
      file: path=/etc/docker state=directory mode=0755

    - name: render /etc/docker/daemon.json
      template: src=daemon.json.j2 dest=/etc/docker/daemon.json


#--------------------------------------------------------------#
# launch docker                                  [docker_launch]
#--------------------------------------------------------------#
- name: launch docker systemd service
  tags: docker_launch
  systemd: name=docker state=restarted enabled=yes daemon_reload=yes


#--------------------------------------------------------------#
# Register Node            [docker_register,register_prometheus]
#--------------------------------------------------------------#
# /etc/prometheus/targets/docker/{{ ip }}.yml
- name: register docker as prometheus target
  tags: [ docker_register, register_prometheus ]
  ignore_errors: true
  delegate_to: '{{ item }}'
  with_items: '{{ groups["infra"] }}'
  copy:
    dest: "{{ prometheus_sd_dir }}/docker/{{ inventory_hostname }}.yml"
    owner: prometheus
    content: |
      # {{ inventory_hostname }} 
      - labels: { ip: {{ inventory_hostname }} , ins: {{ nodename }} , cls: {{ node_cluster|default('nodes') }}  }
        targets: [ {{ inventory_hostname }}:{{ docker_exporter_port }} ]


#--------------------------------------------------------------#
# load docker images cache if exists              [docker_image]
#--------------------------------------------------------------#
- name: load docker images
  tags: docker_image
  ignore_errors: true
  block:

    - name: check docker image cache exists
      stat: path={{ docker_image_cache }}
      register: docker_cache

    - name: load docker image cache if exists
      when: docker_cache.stat.exists
      shell: |
        cat {{ item }} | gzip -d -c - | docker load
      args: { executable: /bin/bash }
      with_fileglob:
        - "/tmp/docker/*.tgz"

...